# Generated by Django 4.2.4 on 2023-09-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_alter_bio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
