# Generated by Django 4.2.5 on 2023-10-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('bio', '0003_alter_bio_body_alter_bio_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='img',
        ),
        migrations.AddField(
            model_name='bio',
            name='images',
            field=models.ManyToManyField(blank=True, to='photo.photo'),
        ),
    ]
