# Generated by Django 4.2.4 on 2023-08-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
        ('social', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to='bio.bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ManyToManyField(blank=True, related_name='social_user', to='social.social'),
        ),
    ]
