# Generated by Django 4.2.4 on 2023-08-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('bio', '0001_initial'),
        ('user', '0002_user_bio_user_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to='bio.bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, related_name='social_user', to='social.social'),
        ),
    ]
