# Generated by Django 4.2.4 on 2023-09-14 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_user_bio', to='bio.bio')),
                ('social', models.ManyToManyField(blank=True, to='social.social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
